# Generated by Django 2.2 on 2020-07-29 08:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chellange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChellangeName', models.CharField(max_length=50)),
                ('ChellangeDesc', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Chellange',
            },
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Contact_uss',
            },
        ),
        migrations.CreateModel(
            name='testMOdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message Field')),
            ],
            options={
                'db_table': 'Test_MOdel',
            },
        ),
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50)),
                ('TopicDesc', models.TextField(blank=True, max_length=1000, null=True)),
                ('voteCount', models.IntegerField(blank=True, default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('Chellange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.Chellange')),
            ],
            options={
                'db_table': 'TopicList',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='janamat/ProfileImage')),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('news_header', models.CharField(max_length=500)),
                ('news', models.TextField(verbose_name='Message Field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Timeline',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edit_Session_Expiry', models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 12, 27, 248874, tzinfo=utc), editable=False)),
                ('message', models.TextField(verbose_name='Message Field')),
                ('Chellange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.Chellange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_votted', models.BooleanField(default=False)),
                ('Chellange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.Chellange')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jmat.TopicList')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Vote',
                'unique_together': {('Chellange', 'User')},
            },
        ),
    ]
