# Generated by Django 2.2 on 2020-07-29 08:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0003_auto_20200729_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edit_Session_Expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 19, 27, 678873, tzinfo=utc), editable=False),
        ),
    ]
