# Generated by Django 2.2 on 2020-07-29 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0006_auto_20200729_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edit_Session_Expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 29, 9, 25, 32, 332761, tzinfo=utc), editable=False),
        ),
    ]
