# Generated by Django 2.2 on 2020-08-02 16:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0007_auto_20200729_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edit_Session_Expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 17, 4, 23, 208885, tzinfo=utc), editable=False),
        ),
    ]
