# Generated by Django 2.2 on 2020-08-14 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0008_auto_20200802_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edit_Session_Expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 16, 26, 27, 536467, tzinfo=utc), editable=False),
        ),
    ]
