# Generated by Django 2.2 on 2020-08-14 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0010_auto_20200814_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edit_Session_Expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 18, 50, 17, 32125, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
