# Generated by Django 2.2 on 2020-08-17 16:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jmat', '0012_auto_20200814_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edit_Session_Expiry',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 17, 53, 16, 544682, tzinfo=utc), editable=False),
        ),
    ]
